version: "3.8"

services:
  postgresql:
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  server:
    restart: always
    build:
      context: ./
      dockerfile: docker/server/server.prod.dockerfile
    ports:
      - "3000:3000"

networks:
  transcendence: