version: "3.8"

services:
  postgresql:
    ports:
      - 5200:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database-volume:/var/lib/postgresql/data

  server:
    build:
      context: ./
      dockerfile: docker/server/backend.dev.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./server/src:/nestjs-server/src
      - ./server/tests:/nestjs-server/tests
      - ./server/uploads:/nestjs-server/uploads

  react-app:
    container_name: react-app
    build:
      context: ./
      dockerfile: docker/server/frontend.dev.dockerfile

    ports:
      - "9000:9000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_FRONTEND_URL=${REACT_APP_FRONTEND_URL}
    networks:
      - transcendence
    volumes:
      - ./react-app/public:/react-app/public
      - ./react-app/src:/react-app/src

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - transcendence
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  transcendence:
