version: "3.8"

services:
  nestjs:
    container_name: nestjs
    networks:
      - transcendence
    depends_on:
      - postgresql
      
  postgresql:
    container_name: postgresql
    networks:
      - transcendence

networks:
  transcendence:
