version: "3.8"

services:
  postgresql:
    build:
      context: ./docker/database
      dockerfile: database.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  nestjs:
    build:
      target: react
      context: ./docker/server
      dockerfile: server.dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app/public:/react-app/public
      - ./react-app/src:/react-app/src
      
networks:
  transcendence:
