version: "3.8"

services:
  postgresql:
    container_name: postgresql
    build:
      context: ./
      dockerfile: docker/database/database.dockerfile
    networks:
      - transcendence

  server:
    container_name: server
    networks:
      - transcendence
    depends_on:
      - postgresql
      
networks:
  transcendence:
