version: "3.8"

services:
  postgresql:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  server:
    build:
      context: ./docker/server
      dockerfile: backend.dev.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./server/src:/nestjs-server/src
      - ./server/tests:/nestjs-server/tests

  react-app:
    container_name: react-app
    build:
      context: ./docker/server
      dockerfile: frontend.dev.dockerfile

    ports:
      - "9000:9000"
    networks:
      - transcendence
    volumes:
      - ./react-app/public:/react-app/public
      - ./react-app/src:/react-app/src

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - transcendence
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  transcendence:
