version: "3.8"

services:
  postgresql:
    restart: always
    build:
      context: ./docker/database
      dockerfile: database.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  nestjs:
    restart: always
    build:
      context: ./
      dockerfile: docker/server/server.prod.Dockerfile
    ports:
      - "3000:3000"

networks:
  transcendence:
