version: "3.8"

services:
  postgresql:
    build:
      context: ./docker/database
      dockerfile: database.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  nestjs:
    build:
      context: ./docker/server
      dockerfile: server.dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app/public:/react-app/public
      - ./react-app/src:/react-app/src
      - ./react-app/test:/react-app/public
      - ./server/src:/nestjs-server/src
      - ./server/test:/nestjs-server/test

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - transcendence
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  transcendence:
