version: "3.8"

services:
  postgresql:
    container_name: postgresql
    build:
      context: ./database/
      dockerfile: database.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - transcendence
  
  server:
    container_name: server
    build:
      context: ./server/
      dockerfile: server.prod.Dockerfile
    networks:
      - transcendence
    ports:
      - "3000:3000"
    depends_on:
      - postgresql

  
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - transcendence
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  transcendence:
